# Use an official Python base image
FROM python:3.9

ENV PYTHONUNBUFFERED 1
ENV PYTHONDONTWRITEBYTECODE 1

RUN apt-get update \
  # dependencies for building Python packages
  && apt-get install -y build-essential \
  # psycopg2 dependencies
  && apt-get install -y libpq-dev \
  # postgres client
  && apt-get install -y postgresql-client

WORKDIR /srv/app

# Requirements are installed here to ensure they will be cached.
COPY requirements.txt .
RUN pip install --upgrade pip
RUN pip install -r requirements.txt

COPY entrypoint.dev.sh /entrypoint.dev.sh

COPY . .

RUN chmod a+x /entrypoint.dev.sh

EXPOSE $PORT

ENTRYPOINT ["/entrypoint.dev.sh"]