# Use an official Python base image
FROM python:3.9

ENV PYTHONUNBUFFERED 1
ENV PYTHONDONTWRITEBYTECODE 1

RUN apt-get update \
  # dependencies for building Python packages
  && apt-get install -y build-essential \
  # psycopg2 dependencies
  && apt-get install -y libpq-dev \
  # postgres client
  && apt-get install -y postgresql-client \
  # install pipx  
  && apt-get install -y  pip \ 
  # install poetry
  && pip install poetry 

WORKDIR /srv/app

# Requirements are installed here to ensure they will be cached.
COPY pyproject.toml . 
COPY poetry.lock .

RUN poetry config virtualenvs.create false
RUN poetry install

COPY entrypoint.dev.sh /entrypoint.dev.sh

COPY . .

RUN chmod a+x /entrypoint.dev.sh

EXPOSE $PORT

ENTRYPOINT ["/entrypoint.dev.sh"]