argcomplete==1.8.1
asgiref==3.8.0
Babel==2.8.0
blinker==1.4
certifi==2024.6.2
charset-normalizer==3.3.2
click==8.0.3
colorama==0.4.4
command-not-found==0.3
cryptography==3.4.8
dbus-python==1.2.18
decorator==4.4.2
distro==1.7.0
distro-info==1.1+ubuntu0.2
Django==5.0.3
django-enum==1.3.1
djangorestframework==3.15.0
drf-yasg==1.21.7
gyp==0.1
httplib2==0.20.2
idna==3.7
imageio==2.34.1
imageio-ffmpeg==0.5.1
importlib-metadata==4.6.4
inflection==0.5.1
jeepney==0.7.1
Jinja2==3.0.3
keyring==23.5.0
launchpadlib==1.10.16
lazr.restfulclient==0.14.4
lazr.uri==1.0.6
livereload==2.6.3
Markdown==3.3.6
MarkupSafe==2.0.1
mkdocs==1.1.2
more-itertools==8.10.0
moviepy==1.0.3
netifaces==0.11.0
numpy==1.26.4
oauthlib==3.2.0
packaging==24.0
pillow==10.3.0
pipx==1.0.0
proglog==0.1.10
psutil==5.9.0
Pygments==2.11.2
PyGObject==3.42.1
pyinotify==0.9.6
PyJWT==2.3.0
pyparsing==2.4.7
python-apt==2.4.0+ubuntu3
pytz==2024.1
PyYAML==5.4.1
requests==2.32.3
SecretStorage==3.3.1
six==1.16.0
sqlparse==0.4.4
systemd-python==234
tornado==6.1
tqdm==4.66.4
typing_extensions==4.10.0
ubuntu-pro-client==8001
ufw==0.36.1
unattended-upgrades==0.1
uritemplate==4.1.1
urllib3==2.2.1
userpath==1.8.0
wadllib==1.3.6
zipp==1.0.0
