# Generated by Django 4.1 on 2024-04-06 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sport',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='sport',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
