# Generated by Django 4.1 on 2024-07-28 11:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0003_recordssport_recordssportuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='recordssportuser',
            name='date_record',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
