# Generated by Django 4.1 on 2024-08-02 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0005_recordssport_general_recordssport_groups'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecordsGroupSport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='sport',
            name='isTheme',
            field=models.BooleanField(default=False, null=True, unique=False),
        ),
        migrations.AlterField(
            model_name='recordssport',
            name='groups',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='sport.recordsgroupsport', unique=True),
        ),
    ]
