# Generated by Django 4.1 on 2024-08-02 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0006_recordsgroupsport_sport_istheme_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recordssport',
            name='general',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='recordssport',
            name='units',
            field=models.CharField(choices=[('weight', 'Kilogrammes'), ('time', 'Temps'), ('distance', 'Distance'), ('points', 'Points'), ('free', 'Personnalisé')], max_length=10),
        ),
    ]
