# Generated by Django 4.1 on 2024-08-02 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0007_alter_recordssport_general_alter_recordssport_units'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recordssport',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
