# Generated by Django 4.1 on 2024-08-02 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0010_rename_weight_value_recordssportuser_record_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='recordssportuser',
            name='free_value',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
