# Generated by Django 4.1 on 2024-08-02 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0011_recordssportuser_free_value'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recordssport',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='recordssport',
            name='order',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
