# Generated by Django 4.1 on 2024-08-04 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0004_alter_workout_workout_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
