# Generated by Django 4.1 on 2024-05-29 09:21

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0003_remove_exercise_description'),
        ('users2', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='injurie',
            name='date',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='exercise.workzone'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='injurie',
            name='zone',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='wellness',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
