# Generated by Django 4.1 on 2024-03-21 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users2', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='size',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
