# Generated by Django 4.1 on 2024-03-22 14:42

from django.db import migrations, models
import users2.models


class Migration(migrations.Migration):

    dependencies = [
        ('users2', '0003_usersfavexercises_injurie'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=users2.models.upload_to),
        ),
    ]
