# Generated by Django 4.1 on 2024-06-05 14:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users2', '0003_alter_injurie_date_alter_injurie_zone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='injurie',
            name='description',
            field=models.CharField(default='Rien à signaler', max_length=256, null=True),
        ),
        migrations.CreateModel(
            name='PasswordChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_modified', models.DateTimeField(auto_now_add=True)),
                ('old_password', models.CharField(max_length=128)),
                ('new_password', models.CharField(max_length=128)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
