# Generated by Django 4.1 on 2024-03-28 09:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users2', '0004_user_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='injurie',
            name='description',
            field=models.CharField(default='Rien à signaler', max_length=256),
        ),
        migrations.AlterField(
            model_name='injurie',
            name='state',
            field=models.CharField(choices=[('TR', 'Soignée'), ('NT', 'Pas soignée'), ('IP', 'En cours')], default='NT', max_length=2),
        ),
        migrations.AlterField(
            model_name='injurie',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_injuries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Wellness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hydratation', models.IntegerField(blank=True, default=0)),
                ('sleep', models.IntegerField(blank=True, default=0)),
                ('stress', models.IntegerField(blank=True, default=0)),
                ('fatigue', models.IntegerField(blank=True, default=0)),
                ('pain', models.IntegerField(blank=True, default=0)),
                ('date', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_wellness', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
