# Generated by Django 4.1 on 2024-06-05 14:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users2', '0004_alter_injurie_description_passwordchangelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordchangelog',
            name='id_user_edited',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_who_edit', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
