# Generated by Django 4.1 on 2024-06-28 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users2', '0005_passwordchangelog_id_user_edited'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='weight',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
