# Generated by Django 4.1 on 2024-03-31 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users2', '0005_alter_injurie_description_alter_injurie_state_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
