# Generated by Django 4.1 on 2024-07-01 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users2', '0006_user_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='injurie',
            name='description',
            field=models.CharField(blank=True, default='Rien à signaler', max_length=256),
        ),
    ]
