# Generated by Django 4.1 on 2024-07-19 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users2', '0007_alter_injurie_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='wellness',
            name='nutrition',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
