# Generated by Django 4.1 on 2024-04-04 09:19

from django.db import migrations, models
import django.db.models.deletion
import exercise.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=255)),
                ('video', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ExerciseMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=255)),
                ('pictures', models.ImageField(blank=True, null=True, upload_to=exercise.models.upload_to)),
            ],
        ),
        migrations.CreateModel(
            name='WorkZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('zone', models.CharField(choices=[('MU', 'Muscle'), ('AR', 'Articulation')], default='MU', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='ExerciseZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zones', to='exercise.exercise')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercise.workzone')),
            ],
        ),
        migrations.CreateModel(
            name='ExerciseStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='exercise.exercise')),
            ],
        ),
        migrations.CreateModel(
            name='ExerciseSport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sports', to='exercise.exercise')),
            ],
        ),
    ]
