# Generated by Django 4.1 on 2024-04-04 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sport', '0001_initial'),
        ('exercise', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercisesport',
            name='sport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sport.sport'),
        ),
        migrations.AddField(
            model_name='exercisematerial',
            name='exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='exercise.exercise'),
        ),
        migrations.AddField(
            model_name='exercisematerial',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercise.material'),
        ),
    ]
