# Generated by Django 4.1 on 2024-03-22 15:56

from django.db import migrations, models
import django.db.models.deletion
import exercise.models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercisematerial',
            name='exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_material', to='exercise.exercise'),
        ),
        migrations.AlterField(
            model_name='exercisestep',
            name='exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercice_steps', to='exercise.exercise'),
        ),
        migrations.AlterField(
            model_name='material',
            name='pictures',
            field=models.ImageField(blank=True, null=True, upload_to=exercise.models.upload_to),
        ),
    ]
