# Generated by Django 4.1 on 2024-05-16 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exercise', '0001_initial'),
        ('sport', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercisesport',
            name='sport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sport.sport'),
        ),
        migrations.AddField(
            model_name='exercisematerial',
            name='exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_exercise', to='exercise.exercise'),
        ),
        migrations.AddField(
            model_name='exercisematerial',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercise.material'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='materials',
            field=models.ManyToManyField(through='exercise.ExerciseMaterial', to='exercise.material'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='muscles',
            field=models.ManyToManyField(through='exercise.ExerciseZone', to='exercise.workzone'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='sports',
            field=models.ManyToManyField(through='exercise.ExerciseSport', to='sport.sport'),
        ),
    ]
