# Generated by Django 4.1 on 2024-03-28 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0002_alter_exercisematerial_exercise_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercisesport',
            name='exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_sports', to='exercise.exercise'),
        ),
        migrations.AlterField(
            model_name='exercisezone',
            name='exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_zone', to='exercise.exercise'),
        ),
        migrations.AlterField(
            model_name='workzone',
            name='zone',
            field=models.CharField(choices=[('MU', 'Muscle'), ('AR', 'Articulation')], default='MU', max_length=2),
        ),
    ]
