# Generated by Django 4.1 on 2024-06-10 17:31

from django.db import migrations, models
import exercise.models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0003_remove_exercise_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=exercise.models.upload_to_thumbnail),
        ),
    ]
