# Generated by Django 4.1 on 2024-04-06 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0003_exercise_created_at_exercise_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercisematerial',
            name='exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials_exercise', to='exercise.exercise'),
        ),
        migrations.AlterField(
            model_name='exercisesport',
            name='exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sports_exercise', to='exercise.exercise'),
        ),
        migrations.AlterField(
            model_name='exercisestep',
            name='exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps_exercise', to='exercise.exercise'),
        ),
        migrations.AlterField(
            model_name='exercisezone',
            name='exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zone_exercise', to='exercise.exercise'),
        ),
    ]
