# Generated by Django 4.1 on 2024-05-02 17:11

from django.db import migrations, models
import django.db.models.deletion
import exercise.models


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0002_sport_created_at_sport_updated_at'),
        ('exercise', '0004_alter_exercisematerial_exercise_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='description',
        ),
        migrations.AddField(
            model_name='exercise',
            name='materials',
            field=models.ManyToManyField(through='exercise.ExerciseMaterial', to='exercise.material'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='sports',
            field=models.ManyToManyField(through='exercise.ExerciseSport', to='sport.sport'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to=exercise.models.upload_to_video),
        ),
        migrations.AlterField(
            model_name='exercisematerial',
            name='exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_exercise', to='exercise.exercise'),
        ),
    ]
