# Generated by Django 4.1 on 2024-07-19 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0005_alter_exercise_name_alter_material_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercisestep',
            name='order',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
