# Generated by Django 4.1 on 2024-05-05 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0006_workzone_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workzone',
            name='id',
        ),
        migrations.AlterField(
            model_name='workzone',
            name='code',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
