# Generated by Django 4.1 on 2024-05-05 22:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0007_remove_workzone_id_alter_workzone_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercisezone',
            name='exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zone_exercises', to='exercise.exercise'),
        ),
    ]
