# Generated by Django 4.1 on 2024-05-06 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0008_alter_exercisezone_exercise'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='zone',
            field=models.ManyToManyField(through='exercise.ExerciseZone', to='exercise.workzone'),
        ),
    ]
