# Generated by Django 4.1 on 2024-05-06 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0009_exercise_zone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exercise',
            old_name='zone',
            new_name='muscles',
        ),
    ]
